11 premium route removal
transitcenter/ted-data pull request #23
Opened 2023-10-12 18:06 UTC by KaiHerrero

File Additions:
- **premium_routes.csv** --> ted-data/ 
   "updated to include premium routes from the 2023 dataset, this needs to be in this specific filepath for 'limitize-routes.py' to 
     work"
- **limitize-routes.py** --> ted-data/
   "script that creates the -limited gtfs dataset, currently places the limited dataset in the same filepath as itself, can be 
     changed"

Comments:

2023-10-12 18:07 UTC, KaiHerrero commented
**desktop.ini** is an unwanted artifact, feel free to delete

2023-10-17 21:56 UTC, wklumpen requested changes

2023-10-17 21:56 UTC, wklumpen commented on ted/gtfs.py
> +def remove_premeium_routes_from_gtfs(gtfs_path: str, output_path: str, premium_routes_path: str):
Couple of things:

- Typo in "premium" in the definition
- If `gtfs_path` is a folder, can you name it `gtfs_folder` for consistency?
- Same comment as above but for `output_path`

2023-10-17 21:56 UTC, wklumpen commented on ted/gtfs.py
> +    os.mkdir(output_path)
Something you can do here is:

``` python
if not os.path.exists(output_folder):
    os.mkdir(output_folder)
```

That way if it already exists it won't throw an error.

2023-10-17 21:56 UTC, wklumpen commented on ted/gtfs.py
> +                print(curr_zip_slug + " is a premium route, skipping...")
Would output `is a premium feed`, since we're skipping the feed entirely (not the route)

2023-10-17 21:56 UTC, wklumpen commented on ted/gtfs.py
> +    print("Done removing premium routes from specified GTFS folder!")
You can add the folder name in here for clarity using f-strings:

``` python 
print(f"Done removing premium routes from {gtfs_folder}!")
```

2023-10-17 22:05 UTC, wklumpen approved these changes

2023-10-17 22:05 UTC, merged